services:
  user-mssql:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      SA_PASSWORD: ApolloProj123
      ACCEPT_EULA: "Y" # Add Persistence
    ports:
      - 1433:1433